services:
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${CONTAINER_PORT}:${SERVER_PORT}"
    volumes:
      - todo-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:${CONTAINER_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
volumes:
  todo-data: 